environment: dev
authDisabled: false
replicaCount:
  web: 1
  api: 1
image:
  web:
    repository: example.azurecr.io/quiz-web
    tag: SET_BY_CI
  api:
    repository: example.azurecr.io/quiz-api
    tag: SET_BY_CI
  pullPolicy: IfNotPresent
service:
  publicIpName: ""
  publicIpResourceGroup: ""
ingress:
  enabled: false
  host: ""
  className: ""
  tlsSecretName: quiz-web-tls
workloadIdentityClientId: ""
tenantId: ""
keyVaultName: ""
postgres:
  host: quiz-postgres
  port: 5432
  database: quiz
  user: quizadmin
  storageClassName: managed-csi
  storage: 8Gi
entra:
  tenantId: ""
  clientId: ""
  audience: ""
  adminGroupId: ""
resources:
  web:
    requests: { cpu: 50m, memory: 64Mi }
    limits: { cpu: 250m, memory: 128Mi }
  api:
    requests: { cpu: 100m, memory: 128Mi }
    limits: { cpu: 500m, memory: 512Mi }
pdb:
  enabled: true
hpa:
  web: { minReplicas: 1, maxReplicas: 3, cpu: 70 }
  api: { minReplicas: 1, maxReplicas: 4, cpu: 70 }
