apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: quiz-web }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: quiz-web }
  minReplicas: {{ .Values.hpa.web.minReplicas }}
  maxReplicas: {{ .Values.hpa.web.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: {{ .Values.hpa.web.cpu }} }
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: { name: quiz-api }
spec:
  scaleTargetRef: { apiVersion: apps/v1, kind: Deployment, name: quiz-api }
  minReplicas: {{ .Values.hpa.api.minReplicas }}
  maxReplicas: {{ .Values.hpa.api.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: {{ .Values.hpa.api.cpu }} }
