apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: quiz-api-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    clientID: {{ .Values.workloadIdentityClientId | quote }}
    keyvaultName: {{ .Values.keyVaultName | quote }}
    tenantId: {{ .Values.tenantId | quote }}
    objects: |
      array:
        - |
          objectName: postgres-admin-password
          objectType: secret
        - |
          objectName: appinsights-connection-string
          objectType: secret
